[build]
cmd = "make build"
bin = "build/debug/loadtoad"
args_bin = ["-v", "--addr=0.0.0.0", "all", "loadtoad"]
include_ext = ["go", "html", "md", "mod", "js", "css"]
exclude_dir = ["build", "client", "gen", "tools", "test/playwright", "data"]
exclude_regex = ["\\.html\\.go$", "_test\\.go$"]
exclude_unchanged = true
delay = 200 # ms
stop_on_error = true
log = "loadtoad_errors.log"
log_time = true
send_interrupt = true

[log]
time = true
